### PR TITLE
Ready for code review

### PR DESCRIPTION
**Pull request by SofiBretz**
Waiting for confirmation.

### CODE REVIEW

**Comment by Ispirett** [comment]
Really excellent !!!!!!! job folks I literally had to watch the URL to know the difference between your site and the original site :1st_place_medal: Just some minor changes to be made, nothing you pros cant handle. 
image


- [ ] for the **section recommendationAndPopular**  instead of using divs microverse requires 
 The left side uses `<figure>` and `<figcaption>` tags followed by the title of the articles
display: flex` or *float* are recommended

- [ ]  All images and videos should be enclosed by a `<figure>` tag with `<figcaption>` that gives a 
 description of the embedded image or video.

- [ ] This is a surprise to me too!!!. But on the bright side i know you folks can do it.
  Any sections that include text (paragraphs) should be wrapped with a `<section/>` tag and include an `<aside/>` tag for Editor's picks and a Sign-Up button. 


Nevertheless, excellent work with this project.  When done with changes please submit this same link for another code review. Happy coding :100:

**Comment by noomdalv** [comment]
All errors fixed, ready for review

**Comment by SofiBretz** [comment]
Hi! How are you? :)

- The "signUpButton" is at the nav bar top right is says "subscribe". 

- The "editorsPicks" section is on the left so if we put <aside> as mentioned on: [https://www.w3schools.com/tags/tag_aside.asp]  
"The <aside> tag defines some content aside from the content it is placed in.
The aside content should be related to the surrounding content."

- We think the "popular" is the content aside , and the "editorsPicks" is a <section>

Thank you for your comments about our project :) Have a great day! ;)

**Review by bolah2009 — APPROVED** [review]
# Congratulations Team! :tada:

You've done an awesome Job :muscle:

#### Important: I strongly recommend checking the positioning of the navbar on 100% zoom (check out the image below) also check the HTML file with [HTML Validator](https://validator.w3.org/#validate_by_input), it is interesting to note that a section (or article) should always have a heading (h1-h6) element ([see this](https://www.w3.org/wiki/HTML/Usage/Headings/Missing)). Consider fixing this before you merge.

| Current | Preffered |
| ----------- | ----------- |
| 100 percent zoom | preffred 100percent menu |


Good luck with your next project
Keep it up :star2:

Cheers
Bola

**Comment by noomdalv** [comment]
Navbar fixed, all done :)

**Review by bolah2009 — COMMENTED** [review]
Am sorry I missed this earlier and didn't address it in the last [comment](https://github.com/noomdalv/Positioning-and-Floating-Elements/pull/1#pullrequestreview-264020228)
> Hi! How are you? :)
> 
> * The "signUpButton" is at the nav bar top right is says "subscribe".
> * The "editorsPicks" section is on the left so if we put  as mentioned on: [https://www.w3schools.com/tags/tag_aside.asp]
>   "The  tag defines some content aside from the content it is placed in.
>   The aside content should be related to the surrounding content."
> * We think the "popular" is the content aside , and the "editorsPicks" is a
> 
> Thank you for your comments about our project :) Have a great day! ;)

The editor's pick and sign up button @Ispirett is referring to is at the far right of the page which is a valid sectional element `<aside>`, the picture below. 

### Sign up button
sign up

### Editor's pick
editor's pick

> The HTML `<aside>` element represents a portion of a document whose content is only indirectly related to the document's main content. Asides are frequently presented as sidebars or call-out boxes.

Here the `Sign-up button` and the `editor's pick` is a call-out box that is not directly related to the main content itself.

### Learn more about aside [here on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/aside) and also on the [HTML specification](https://html.spec.whatwg.org/multipage/sections.html#the-aside-element) page.

**Pull request merged**
